const API_URL='https://script.google.com/macros/s/AKfycby2SNa8Fx258tUi3UUDVHNGAqOWg80VYx3I5dSavJnhpMbJaNV-TidNYUh9PxhNnr-fNw/exec';
const DATA={"prefectures":[{"id":"01_okinawa","key":"okinawa","name":"沖縄県","reading":"おきなわけん","badges":[{"name":"首里城","file":"01_shurijo.png"},{"name":"美ら海水族館","file":"02_churaumi_aquarium.png"},{"name":"沖縄そば","file":"03_okinawa_soba.png"},{"name":"紅いもタルト","file":"04_beniimo_tart.png"},{"name":"タコライス","file":"05_taco_rice.png"},{"name":"南国フルーツ","file":"06_tropical_fruits.png"},{"name":"琉球ガラス","file":"07_ryukyu_glass.png"},{"name":"もずく","file":"08_mozuku.png"},{"name":"古宇利大橋","file":"09_kouri_bridge.png"},{"name":"竹富島","file":"10_taketomi_island.png"}]},{"id":"02_kagoshima","key":"kagoshima","name":"鹿児島県","reading":"かごしまけん","badges":[{"name":"桜島","file":"01_sakurajima.png"},{"name":"鹿児島城跡","file":"02_kagoshima_castle.png"},{"name":"黒豚しゃぶしゃぶ","file":"03_kurobuta_shabushabu.png"},{"name":"知覧武家屋敷庭園","file":"04_chiran_samurai_garden.png"},{"name":"屋久島","file":"05_yakushima.png"},{"name":"出水麓","file":"06_izumi_fumoto.png"},{"name":"さつまいも","file":"07_satsumaimo.png"},{"name":"長島","file":"08_nagashima.png"},{"name":"霧島高原","file":"09_kirishima_highlands.png"},{"name":"芋焼酎","file":"10_imo_shochu.png"}]}]};
const STORAGE_KEY='sjj_state_v5_multi';
const PROFILE_KEY='sjj_profile_v1';
const defaultState={totalSeconds:0,running:false,sessionStartSeconds:0,serverWeeklyMinutes:0,serverTotalMinutes:0};
let state=Object.assign({},defaultState,JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));
let profile=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');
let interval=null,selectedPref=0,mapPreviewMode='auto',syncing=false;
const pageTitles={home:'Home',timer:'Timer',collection:'Journey Collection',map:'Journey Map',friends:'Journey Friends'};

function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function saveProfile(){localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));}
function uid(){return 'SJ-'+crypto.getRandomValues(new Uint32Array(2)).join('-')+'-'+Date.now().toString(36);}
function initials(name=''){return [...name.trim()].slice(0,2).join('').toUpperCase()||'SJ';}
function formatTime(s){const h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor((s%3600)/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');return `${h}:${m}:${sec}`;}
function unlockedCount(){return Math.min(20,Math.floor(state.totalSeconds/600));}
function currentPrefecture(){return unlockedCount()>=10?'鹿児島県':'沖縄県';}
function toast(message,type='ok'){const el=document.getElementById('syncToast');el.textContent=message;el.className=`sync-toast show ${type}`;clearTimeout(el._t);el._t=setTimeout(()=>el.className='sync-toast',3000);}
function showScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.target===name));document.getElementById('pageTitle').textContent=pageTitles[name];if(name==='friends')loadRanking();window.scrollTo({top:0,behavior:'smooth'});}
async function apiPost(params){const body=new URLSearchParams(params);const r=await fetch(API_URL,{method:'POST',body});if(!r.ok)throw new Error(`通信エラー (${r.status})`);const data=await r.json();if(!data.success)throw new Error(data.message||'処理に失敗しました');return data;}
async function register(event){event.preventDefault();const btn=document.getElementById('registerSubmit'),msg=document.getElementById('registerMessage');btn.disabled=true;msg.textContent='登録しています…';try{const candidate={userId:profile?.userId||uid(),nickname:document.getElementById('nicknameInput').value.trim(),faculty:document.getElementById('facultyInput').value.trim(),department:document.getElementById('departmentInput').value.trim(),teacherEmail:document.getElementById('teacherEmailInput').value.trim()};await apiPost({action:'register',...candidate});profile=candidate;saveProfile();updateProfileUI();document.getElementById('registerDialog').close();toast('参加者登録が完了しました');loadRanking();}catch(e){msg.textContent='登録できませんでした：'+e.message;}finally{btn.disabled=false;}}
function openProfile(){if(profile){document.getElementById('nicknameInput').value=profile.nickname||'';document.getElementById('facultyInput').value=profile.faculty||'';document.getElementById('departmentInput').value=profile.department||'';document.getElementById('teacherEmailInput').value=profile.teacherEmail||'';}document.getElementById('registerMessage').textContent='';document.getElementById('registerDialog').showModal();}
function updateProfileUI(){document.getElementById('profileBtn').textContent=initials(profile?.nickname);document.querySelector('.avatar.big').textContent=initials(profile?.nickname);}
async function syncSession(minutes){if(!profile||minutes<=0||syncing)return;syncing=true;toast(`${minutes}分を記録しています…`);try{const data=await apiPost({action:'addStudy',userId:profile.userId,minutes:String(minutes),currentPrefecture:currentPrefecture()});state.serverWeeklyMinutes=data.weeklyMinutes||0;state.serverTotalMinutes=data.totalMinutes||0;save();toast(`${minutes}分をランキングへ反映しました`);loadRanking();}catch(e){toast('記録の送信に失敗しました：'+e.message,'error');}finally{syncing=false;}}
function toggleTimer(){if(!profile){openProfile();return;}if(!state.running){state.running=true;state.sessionStartSeconds=state.totalSeconds;interval=setInterval(()=>{state.totalSeconds++;save();renderAll();},1000);}else{state.running=false;clearInterval(interval);interval=null;const elapsed=state.totalSeconds-state.sessionStartSeconds;state.sessionStartSeconds=state.totalSeconds;save();const minutes=Math.floor(elapsed/60);if(minutes>0)syncSession(minutes);else toast('1分未満のためランキングにはまだ加算されません');}renderAll();}
function resetTimer(){if(state.running){toast('タイマーを停止してからリセットしてください','error');return;}state.totalSeconds=0;state.sessionStartSeconds=0;save();renderAll();}

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>showScreen(b.dataset.target));document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>showScreen(b.dataset.nav));document.getElementById('homeStart').onclick=toggleTimer;document.getElementById('timerStart').onclick=toggleTimer;document.getElementById('resetBtn').onclick=resetTimer;document.getElementById('profileBtn').onclick=openProfile;document.getElementById('registerForm').addEventListener('submit',register);document.getElementById('refreshRanking').onclick=loadRanking;
const tabs=document.getElementById('prefTabs');DATA.prefectures.forEach((p,i)=>{const b=document.createElement('button');b.textContent=p.name;b.onclick=()=>{selectedPref=i;renderCollection();};tabs.appendChild(b);});
function renderCollection(){const unlocked=unlockedCount(),p=DATA.prefectures[selectedPref];[...tabs.children].forEach((b,i)=>b.classList.toggle('active',i===selectedPref));document.getElementById('prefReading').textContent=p.reading;document.getElementById('prefTitle').textContent=p.name;const prefUnlocked=Math.max(0,Math.min(10,unlocked-selectedPref*10));document.getElementById('prefCount').textContent=`${prefUnlocked} / 10`;document.getElementById('collectionProgress').textContent=`${unlocked} / 20`;const grid=document.getElementById('badgeGrid');grid.innerHTML='';p.badges.forEach((badge,i)=>{const globalIndex=selectedPref*10+i,isUnlocked=globalIndex<unlocked,btn=document.createElement('button');btn.className='badge-card'+(isUnlocked?'':' locked');const path=`Assets/badges/${p.id}/${badge.file}`;btn.innerHTML=`<div class="badge-wrap"><img src="${path}" alt="${isUnlocked?badge.name:'未取得バッジ'}"><div class="lock-icon">?</div></div><small>${String(i+1).padStart(2,'0')}</small><strong>${isUnlocked?badge.name:'未取得'}</strong>`;if(isUnlocked)btn.onclick=()=>openBadge(path,p.name,badge.name);grid.appendChild(btn);});}
const dialog=document.getElementById('badgeDialog');function openBadge(path,pref,name){document.getElementById('dialogImage').src=path;document.getElementById('dialogPref').textContent=pref;document.getElementById('dialogName').textContent=name;dialog.showModal();}document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
function updateMap(){const unlocked=unlockedCount();let completed=Math.floor(unlocked/10);if(mapPreviewMode!=='auto')completed=Number(mapPreviewMode);const ok=document.getElementById('okinawaOverlay'),kg=document.getElementById('kagoshimaOverlay');ok.className='map-layer overlay';kg.className='map-layer overlay';if(completed>=1)ok.classList.add('complete');else ok.classList.add('current');if(completed>=2)kg.classList.add('complete');else if(completed>=1)kg.classList.add('current');document.getElementById('okinawaMapStatus').textContent=`${Math.max(0,Math.min(10,unlocked))} / 10`;document.getElementById('kagoshimaMapStatus').textContent=`${Math.max(0,Math.min(10,unlocked-10))} / 10`;const current=completed>=2?'宮崎県':completed>=1?'鹿児島県':'沖縄県';document.getElementById('mapCurrentPref').textContent=current;document.getElementById('mapCurrentText').textContent=completed>=2?'次の目的地、宮崎県のバッジを準備中です。':`${current}の10個の思い出を集めましょう。`;}
document.querySelectorAll('[data-map-preview]').forEach(btn=>{btn.onclick=()=>{mapPreviewMode=btn.dataset.mapPreview;document.querySelectorAll('[data-map-preview]').forEach(b=>b.classList.toggle('active',b===btn));updateMap();};});
function renderAll(){const unlocked=unlockedCount(),mins=Math.floor(state.totalSeconds/60),flat=DATA.prefectures.flatMap(p=>p.badges.map(b=>b.name));document.getElementById('homeTimer').textContent=formatTime(state.totalSeconds);document.getElementById('timerDisplay').textContent=formatTime(state.totalSeconds);document.getElementById('todayMinutes').textContent=`${mins} min`;document.getElementById('weekMinutes').textContent=`${state.serverWeeklyMinutes||mins} min`;document.getElementById('homeProgressText').textContent=`${unlocked} / 470 Memories`;document.getElementById('mapProgress').textContent=`${unlocked} / 470 Memories`;document.getElementById('homeProgressFill').style.width=`${unlocked/470*100}%`;document.getElementById('nextDestination').textContent=flat[Math.min(unlocked,flat.length-1)];const rem=10-(mins%10||0);document.getElementById('nextBadgeText').textContent=unlocked>=20?'次の県を準備中':`あと${rem}分`;document.getElementById('homeStart').textContent=state.running?'PAUSE':'START';document.getElementById('timerStart').textContent=state.running?'PAUSE':'START';const currentPref=currentPrefecture();document.getElementById('currentChip').textContent=`現在地：${currentPref}`;document.getElementById('myJourneyText').textContent=`${currentPref}・${unlocked} Memories`;document.getElementById('myJourneyMinutes').textContent=`${state.serverWeeklyMinutes||0} min`;renderCollection();updateMap();}
async function loadRanking(){const status=document.getElementById('rankingStatus'),list=document.getElementById('friendsList');status.textContent='読み込み中…';try{const r=await fetch(`${API_URL}?action=ranking&_=${Date.now()}`);if(!r.ok)throw new Error(`通信エラー (${r.status})`);const data=await r.json();if(!data.success)throw new Error(data.message||'取得に失敗しました');renderRanking(data.ranking||[]);status.textContent=`${data.ranking.length}人が今週の旅に参加中`;}catch(e){status.textContent='ランキングを取得できませんでした';list.innerHTML=`<div class="empty-ranking">${e.message}<br>Apps Scriptの公開設定が「全員」になっているか確認してください。</div>`;}}
function renderRanking(rows){const list=document.getElementById('friendsList');list.innerHTML='';if(!rows.length){list.innerHTML='<div class="empty-ranking">まだランキング記録がありません。<br>タイマーを1分以上動かして停止すると反映されます。</div>';return;}rows.forEach(row=>{const mine=profile&&row.userId===profile.userId;if(mine){state.serverWeeklyMinutes=Number(row.weeklyMinutes)||0;state.serverTotalMinutes=Number(row.totalMinutes)||0;save();document.getElementById('myJourneyMinutes').textContent=`${state.serverWeeklyMinutes} min`;}const div=document.createElement('div');div.className='friend-row'+(mine?' mine':'');div.innerHTML=`<span class="rank-no">${row.rank}</span><div class="avatar">${initials(row.nickname)}</div><div><strong>${escapeHtml(row.nickname)}${mine?'（あなた）':''}</strong><small>${escapeHtml(row.currentPrefecture||'沖縄県')} ${row.faculty?'・'+escapeHtml(row.faculty):''}</small></div><span>${Number(row.weeklyMinutes)||0} min</span><button type="button">エール</button>`;div.querySelector('button').onclick=()=>toast(`${row.nickname}さんにエールを送りました（試作表示）`);list.appendChild(div);});}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
state.running=false;save();updateProfileUI();renderAll();showScreen('home');if(!profile)setTimeout(openProfile,400);else loadRanking();
